version: "3.9"

services:
  postgresdb:
    image: postgres:14.5-bullseye
    restart: always
    volumes:
      - "postgresdb_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "nodejs-rest-api-dev"
    ports:
      - "5430:5432"
    networks:
      - infra

  redis:
    image: redis:7.0.4-bullseye
    restart: always
    ports:
      - 6379:6379
    networks:
      - infra

networks:
  infra:

volumes:
  postgresdb_data:
  mongodb_data:
